# Test demo
import time

import board
import busio

import adafruit_ssd1306
import adafruit_vl53l0x

# Initialize I2C bus
i2c = busio.I2C(board.SCL, board.SDA)
vl53 = adafruit_vl53l0x.VL53L0X(i2c)
oled = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c)

text = 'Hello'

#make a stupid-ass letter 'T'
#make it 6x6 and with 2 pixels thick
oled.fill(0)
#oled.pixel(0,0,1)
#oled.pixel(1,0,1)
#oled.pixel(2,0,1)
#oled.pixel(3,0,1)
#oled.pixel(4,0,1)
#oled.pixel(2,1,1)
#oled.pixel(2,2,1)
#oled.pixel(2,3,1)
#oled.pixel(2,4,1)
#oled.show()

# Optionally adjust the measurement timing budget to change speed and accuracy.
# See the example here for more details:
#   https://github.com/pololu/vl53l0x-arduino/blob/master/examples/Single/Single.ino
# For example a higher speed but less accurate timing budget of 20ms:
#vl53.measurement_timing_budget = 20000
# Or a slower but more accurate timing budget of 200ms:
#vl53.measurement_timing_budget = 200000
# The default timing budget is 33ms, a good compromise of speed and accuracy.

# Main loop will read the range and print it every second.
while True:
    time.sleep(1.0)
    num = 0
    xStart = 0
    yStart = 8
    range = format(vl53.range)
    print('Range: %smm' % (range))

    L = list(range)
    for x in L:
        if x == '0':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart, yStart + 1, 1)
            oled.pixel(xStart, yStart + 2, 1)
            oled.pixel(xStart, yStart + 3, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart, yStart + 5, 1)
            oled.pixel(xStart, yStart + 6, 1)
            oled.pixel(xStart, yStart + 7, 1)
            oled.pixel(xStart, yStart + 8, 1)
            oled.pixel(xStart, yStart + 9, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 1, yStart + 9, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 3, yStart + 9, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
        if x == '1':
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 2, yStart + 1, 1)
            oled.pixel(xStart + 2, yStart + 2, 1)
            oled.pixel(xStart + 2, yStart + 3, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 5, 1)
            oled.pixel(xStart + 2, yStart + 6, 1)
            oled.pixel(xStart + 2, yStart + 7, 1)
            oled.pixel(xStart + 2, yStart + 8, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
        if x == '2':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart, yStart + 5, 1)
            oled.pixel(xStart, yStart + 6, 1)
            oled.pixel(xStart, yStart + 7, 1)
            oled.pixel(xStart, yStart + 8, 1)
            oled.pixel(xStart, yStart + 9, 1)
            oled.pixel(xStart + 1, yStart + 9, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
            oled.pixel(xStart + 3, yStart + 9, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
        if x == '3':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
            oled.pixel(xStart + 3, yStart + 9, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
            oled.pixel(xStart + 1, yStart + 9, 1)
            oled.pixel(xStart, yStart + 9, 1)
        if x == '4':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart, yStart + 1, 1)
            oled.pixel(xStart, yStart + 2, 1)
            oled.pixel(xStart, yStart + 3, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
        if x == '5':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart, yStart + 1, 1)
            oled.pixel(xStart, yStart + 2, 1)
            oled.pixel(xStart, yStart + 3, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
            oled.pixel(xStart + 3, yStart + 9, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
            oled.pixel(xStart + 1, yStart + 9, 1)
            oled.pixel(xStart, yStart + 9, 1)
        if x == '6':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart, yStart + 1, 1)
            oled.pixel(xStart, yStart + 2, 1)
            oled.pixel(xStart, yStart + 3, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
            oled.pixel(xStart + 3, yStart + 9, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
            oled.pixel(xStart + 1, yStart + 9, 1)
            oled.pixel(xStart, yStart + 9, 1)
            oled.pixel(xStart, yStart + 8, 1)
            oled.pixel(xStart, yStart + 7, 1)
            oled.pixel(xStart, yStart + 6, 1)
            oled.pixel(xStart, yStart + 5, 1)
        if x == '7':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
        if x == '8':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)
            oled.pixel(xStart + 3, yStart + 9, 1)
            oled.pixel(xStart + 2, yStart + 9, 1)
            oled.pixel(xStart + 1, yStart + 9, 1)
            oled.pixel(xStart, yStart + 9, 1)
            oled.pixel(xStart, yStart + 8, 1)
            oled.pixel(xStart, yStart + 7, 1)
            oled.pixel(xStart, yStart + 6, 1)
            oled.pixel(xStart, yStart + 5, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart, yStart + 3, 1)
            oled.pixel(xStart, yStart + 2, 1)
            oled.pixel(xStart, yStart + 1, 1)
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
        if x == '9':
            oled.pixel(xStart, yStart, 1)
            oled.pixel(xStart + 1, yStart, 1)
            oled.pixel(xStart + 2, yStart, 1)
            oled.pixel(xStart + 3, yStart, 1)
            oled.pixel(xStart + 4, yStart, 1)
            oled.pixel(xStart + 4, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 2, 1)
            oled.pixel(xStart + 4, yStart + 3, 1)
            oled.pixel(xStart + 4, yStart + 4, 1)
            oled.pixel(xStart + 3, yStart + 4, 1)
            oled.pixel(xStart + 2, yStart + 4, 1)
            oled.pixel(xStart + 1, yStart + 4, 1)
            oled.pixel(xStart, yStart + 4, 1)
            oled.pixel(xStart, yStart + 3, 1)
            oled.pixel(xStart, yStart + 2, 1)
            oled.pixel(xStart, yStart + 1, 1)
            oled.pixel(xStart + 4, yStart + 5, 1)
            oled.pixel(xStart + 4, yStart + 6, 1)
            oled.pixel(xStart + 4, yStart + 7, 1)
            oled.pixel(xStart + 4, yStart + 8, 1)
            oled.pixel(xStart + 4, yStart + 9, 1)

        num += 1
        xStart += 6

    oled.pixel(xStart, yStart + 4, 1)
    oled.pixel(xStart, yStart + 5, 1)
    oled.pixel(xStart, yStart + 6, 1)
    oled.pixel(xStart, yStart + 7, 1)
    oled.pixel(xStart, yStart + 8, 1)
    oled.pixel(xStart, yStart + 9, 1)
    oled.pixel(xStart + 1, yStart + 5, 1)
    oled.pixel(xStart + 2, yStart + 4, 1)
    oled.pixel(xStart + 2, yStart + 5, 1)
    oled.pixel(xStart + 2, yStart + 6, 1)
    oled.pixel(xStart + 2, yStart + 7, 1)
    oled.pixel(xStart + 2, yStart + 8, 1)
    oled.pixel(xStart + 2, yStart + 9, 1)
    oled.pixel(xStart + 3, yStart + 5, 1)
    oled.pixel(xStart + 4, yStart + 6, 1)
    oled.pixel(xStart + 4, yStart + 7, 1)
    oled.pixel(xStart + 4, yStart + 8, 1)
    oled.pixel(xStart + 4, yStart + 9, 1)

    num += 1
    xStart += 6

    oled.pixel(xStart, yStart + 4, 1)
    oled.pixel(xStart, yStart + 5, 1)
    oled.pixel(xStart, yStart + 6, 1)
    oled.pixel(xStart, yStart + 7, 1)
    oled.pixel(xStart, yStart + 8, 1)
    oled.pixel(xStart, yStart + 9, 1)
    oled.pixel(xStart + 1, yStart + 5, 1)
    oled.pixel(xStart + 2, yStart + 4, 1)
    oled.pixel(xStart + 2, yStart + 5, 1)
    oled.pixel(xStart + 2, yStart + 6, 1)
    oled.pixel(xStart + 2, yStart + 7, 1)
    oled.pixel(xStart + 2, yStart + 8, 1)
    oled.pixel(xStart + 2, yStart + 9, 1)
    oled.pixel(xStart + 3, yStart + 5, 1)
    oled.pixel(xStart + 4, yStart + 6, 1)
    oled.pixel(xStart + 4, yStart + 7, 1)
    oled.pixel(xStart + 4, yStart + 8, 1)
    oled.pixel(xStart + 4, yStart + 9, 1)

    num += 1
    xStart += 6

    oled.show()
    oled.fill(0)
